apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-pulse.fullname" . }}-config
  labels:
    {{- include "kube-pulse.labels" . | nindent 4 }}
data: # Bu kod, values.yaml içindeki her config değerini Kubernetes ConfigMap verisine dönüştürür.
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
